// Code generated by "stringer -type Kind -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[Error-1]
	_ = x[Comment-2]
	_ = x[Eq-3]
	_ = x[RawString-4]
	_ = x[String-5]
	_ = x[Ident-6]
	_ = x[VarInterp-7]
	_ = x[CmdInterp-8]
}

const _Kind_name = "EOFErrorCommentEqRawStringStringIdentVarInterpCmdInterp"

var _Kind_index = [...]uint8{0, 3, 8, 15, 17, 26, 32, 37, 46, 55}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
